services:
  - type: web
    name: alist-render
    env: docker
    plan: free
    region: singapore
    envVars:
      - key: DB_TYPE
        value: mysql
      - key: DB_HOST
        value: sql12.freesqldatabase.com
      - key: DB_PORT
        value: "3306"
      - key: DB_NAME
        value: sql12834058
      - key: DB_USER
        value: sql12834058
      - key: DB_PASS
        sync: false
